sudo: required
services:
  - docker

before_install:
  - docker build -t hady207/react-test -f ./client/dockerfile.dev ./client

script:
  - docker run -e CI=true  hady207/react-test npm test

after_success:
  - docker build -t hady207/multi-client ./client
  - docker build -t hady207/multi-nginx ./nginx
  - docker build -t hady207/multi-server ./server
  - docker build -t hady207/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push it to docker hub
  - docker push hady207/multi-client
  - docker push hady207/multi-nginx
  - docker push hady207/multi-server
  - docker push hady207/multi-worker
